# PA 3: Association Analysis - Apriori Algorithm

## Student Details

First Student Name and ID: Harsh Artwani 1001953350

Other Group Members:
Second Student Name and ID: Gaurav Nale 1001859699
Third Student Name and ID: Kunal Nagdev 1001934124

NO REPORT REQUIRED

## Submission Instructions


Step 1: Create a folder and name it 'lastname_firstname_yourNetID_PA4'

Step 2: Rename this submission file as 'lastname_firstname_yourNetID_PA4.ipynb' and place it inside the folder 'lastname_firstname_yourNetID_PA4'

Step 3: Rename the updated dataset file 'dataset.csv' and place it inside the folder 'lastname_firstname_yourNetID_PA4'  

Step 4: Your submission folder should include ONLY the following files:
    * apriory.py,
    * lastname_firstname_yourNetID_PA4.ipynb, 
    * dataset.csv,
    * toyDS.csv

Step 5: Zip this folder and submit it on Canvas. Your final submission folder name should be 'lastname_firstname_yourNetID_PA4.ZIP'

## Programming Assignment Details

Before you start:
- Be familiar with the algorithm and with the dataset.
- If you use external sources make sure that you cite them, and be specific! 
- Make sure that your code is running before you upload your submission file. TA will not debug your code.
- Start early!


For this assignment, you will have to use:
* Jupyter notebook, 
* the dataset [01],
* and the Apriori Algorithm (apriory.py)[02]. Note that the apriory.py file is modified to run with Python 3.
* and the FPgrowth Algorithm [03].

NOTE : Each team will have a total of 3 .ipynb file. Each member will work on a different dataset.csv file

The datasets to be used are :

1.Market_Basket_Optimisation.csv

2.bread basket.csv

3.Groceries_dataset.csv

## - - - - - - - - - - - - - - - - - - - - - - - SOLUTION - - - - - - - - - - - - - - - - - - - - - - -

In [16]:
%%javascript
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

In [2]:
# Import your Libraries
import pandas as pd
from pandas import DataFrame
import csv
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import fpgrowth
from mlxtend.frequent_patterns import association_rules
import apriori
from apriori import runApriori
from apriori import printResults
from apriori import dataFromFile
from apriori import joinSet
from apriori import subsets
from IPython.display import Image
# Above are the only libraries you can use. Do not make any changes above.
# -10 will be deducted, if you use additional libraries apart from these.

### Task 1: DataSet Preprocess
Before you start you need to modify your dataset 'dataset_group.csv' to look like the toyDS.csv.  Each transaction is at one line with a variable length.

Export your modified dataset in a file named 'dataset.csv'.

Use pandas to Read and Print the first 7 transactions of the 'dataset.csv'.

In [18]:
#from IPython.display import Image
#print ('ScreenShot of the toyDS.csv')
#Image("SampleScreen01.png")

In [3]:
# # # # # # # # #  Code for Task 1 # # # # # # # # #

# mbo in prefix stands for Market Basket Optimization
mbo_data = pd.read_csv('Groceries_dataset.csv',header=None)

# Print first 7 values
mbo_data.head(8)

               0           1                 2
0  Member_number        Date   itemDescription
1           1808  21-07-2015    tropical fruit
2           2552    5/1/2015        whole milk
3           2300  19-09-2015         pip fruit
4           1187  12/12/2015  other vegetables
5           3037    1/2/2015        whole milk
6           4941  14-02-2015        rolls/buns
7           4501    8/5/2015  other vegetables

In [6]:
mbo_data.values.tolist()

# Creating empty list to contain all the values in comma separated format.
dataToList = []
for index in range(1, len(mbo_data)):
    dataToList.append([str(mbo_data.values[index,j]) for j in range(0,3) if str(mbo_data.values[index,j])!='nan']) 

# Printing first 7 values of the list
dataToList[0:7]

[['1808', '21-07-2015', 'tropical fruit'],
 ['2552', '5/1/2015', 'whole milk'],
 ['2300', '19-09-2015', 'pip fruit'],
 ['1187', '12/12/2015', 'other vegetables'],
 ['3037', '1/2/2015', 'whole milk'],
 ['4941', '14-02-2015', 'rolls/buns'],
 ['4501', '8/5/2015', 'other vegetables']]

In [5]:
# Create a new file with variable 'file'
file = open('dataset.csv', 'w', newline = '\n')
for i in dataToList[1:]:
    fileWriter = csv.writer(file)
    fileWriter.writerow(i)
new_dataset_file = pd.read_csv('dataset.csv', header = None);

# Filling NA with empty space
new_dataset = new_dataset_file.fillna('')
new_dataset.head(7)

      0           1                 2
0  2552    5/1/2015        whole milk
1  2300  19-09-2015         pip fruit
2  1187  12/12/2015  other vegetables
3  3037    1/2/2015        whole milk
4  4941  14-02-2015        rolls/buns
5  4501    8/5/2015  other vegetables
6  3803  23-12-2015        pot plants

### Task 2: Run apriory.py and Evaluate Results 

In this task, you have to find how you will be able to execute and print apriory results by making use only the apriory.py. In other words "DO NOT USE ANY OTHER LIBRARY FOR TASK 2!!!". 

(*) For those that are not familiar with python and coding this could be a quite demanding task.


You will have to execute apriori algorithm "3" times for different combinations of support and confidence.
Print the results of apriory for 'dataset.csv' by making use ONLY the provided methods. 

Do not forget to add your reasoning (explain the result outcome) at the top of each case in a nice and readable way. 

You are allowed to use the python print method to print your results. DO NOT add your reasoning as comments.

In [47]:
print ('# # # # # # # # #  Code for Task 2, Case:1 # # # # # # # # #') 
print ('Case 1 (minimum support=0.0002 and minimum confidence=0.9)')
print ('Case 1 Reasoning: This took extremely long time to generate rules. At a glance, there are many rules with confidence = 1. We get many rules for minimum support of 0.0001 and minimum threshold of 0.0015. More rules means better association of items and their chance of reccurence. Here we have a maximum support for id 1669 and date 19-08-2015 combination(s = 0.000232 and confidence = 1).')
print ('Case 1 Output:')
!python3 apriori.py -f dataset.csv -s 0.0001 -c 0.0015

# # # # # # # # #  Code for Task 2, Case:1 # # # # # # # # #
Case 1 (minimum support=0.0002 and minimum confidence=0.9)
Case 1 Reasoning:
Case 1 Output:
^C
Traceback (most recent call last):
  File "/Users/kunalnagdev/work/college_work/subject_docs/data_mining/assignment_3/PA3FALL2021/1001934124_1001953350_1001859699PA3/Artwani_3350/apriori.py", line 172, in <module>
    items, rules = runApriori(inFile, minSupport, minConfidence)
  File "/Users/kunalnagdev/work/college_work/subject_docs/data_mining/assignment_3/PA3FALL2021/1001934124_1001953350_1001859699PA3/Artwani_3350/apriori.py", line 87, in runApriori
    currentCSet = returnItemsWithMinSupport(currentLSet,
  File "/Users/kunalnagdev/work/college_work/subject_docs/data_mining/assignment_3/PA3FALL2021/1001934124_1001953350_1001859699PA3/Artwani_3350/apriori.py", line 31, in returnItemsWithMinSupport
    if item.issubset(transaction):
KeyboardInterrupt

In [ ]:
print ('# # # # # # # # #  Code for Task 2, Case:2 # # # # # # # # #') 
print ('Case 2 (minimum support=0.000025 and minimum confidence=0.5)')
print ('Case 2 Reasoning: Took long time to generate rules. At a glance, there are many rules with confidence = 1. We get many rules for minimum support of 0.0001 and minimum threshold of 0.0015. More rules means better association of items and their chance of reccurence. Here we have a maximum support for id 1669 and date 19-08-2015 combination(s = 0.000232 and confidence = 1).')
print ('Case 2 Output:')
!python3 apriori.py -f dataset.csv -s 0.000025 -c 0.5

# # # # # # # # #  Code for Task 2, Case:2 # # # # # # # # #
Case 2 (minimum support=0.015 and minimum confidence=0.15)
Case 2 Reasoning: We get moderate confidance in following rule ("soup", ) ==> ("mineral water") , Confidence: 0.456 . Its clear that increasing threshhold value creates lower rules, but the confidence of the rules is more. Thus, if people purchase "soup" together then there is 45.6% chance that they will also going to purchase "mineral water" along with those items.
Case 2 Output:

------------ITEMS-----------------
item: ('newspapers',) , 0.015
item: ('whipped/sour cream',) , 0.017
item: ('bottled beer',) , 0.018
item: ('canned beer',) , 0.019
item: ('shopping bags',) , 0.019
item: ('pip fruit',) , 0.019
item: ('pastry',) , 0.020
item: ('citrus fruit',) , 0.021
item: ('sausage',) , 0.024
item: ('bottled water',) , 0.024
item: ('tropical fruit',) , 0.027
item: ('root vegetables',) , 0.028
item: ('yogurt',) , 0.034
item: ('soda',) , 0.039
item: ('rolls/buns',) , 0.044
item: ('other vegetables',) , 0.049
item: ('whole milk',) , 0.065

------------RULES-----------------

In [71]:
print ('# # # # # # # # #  Code for Task 2, Case:3 # # # # # # # # #') 
print ('Case 3 (minimum support=0.00005 and minimum confidence=0.07)')
print ('Case 3 Reasoning: Took long time to generate rules.  We get very less rules for minimum support of 0.00005 and but with very strong confidence of 1.0 at min confidence threshhold 0.07. Here we have a maximum support of 0.000232 with confidence 1.Rule is with antecedent 1669 and consequent as 19-08-2015')
print ('Case 3 Output:')
!python3 apriori.py -f dataset.csv -s 0.00005 -c 0.07

# # # # # # # # #  Code for Task 2, Case:3 # # # # # # # # #
Case 3 (minimum support=0.00005 and minimum confidence=0.07)
Case 3 Reasoning: Took long time to generate rules.
Case 3 Output:

### Task 3: Run FPgrowth and Evaluate Results 
In this task, you have to find how you will be able to execute and print FPgrowth results using mlxtend.
In other words "DO NOT USE ANY OTHER LIBRARY FOR TASK 2!!!".

(*) For those that are not familiar with python and coding this could be a quite demanding task.

You will have to execute apriori algorithm "3" times for different combinations of support and confidence. Print the results of FPgrowth for 'dataset.csv'. 

Do not forget to add your reasoning (explain the result outcome) at the top of each case in a nice and readable way.

In [42]:
print ('# # # # # # # # #  Code for Task 3, Case:1 # # # # # # # # #') 
transaction_encoder = TransactionEncoder()
transaction_encoder_array = transaction_encoder.fit(dataToList).transform(dataToList)
df = pd.DataFrame(transaction_encoder_array, columns=transaction_encoder.columns_)
frequent_itemsets=fpgrowth(df, min_support=0.0001, use_colnames=True)
print ('Case 1 (minimum support=0.0001)')
print ('Case 1 Reasoning: At a glance, there are many rules with confidence = 1. We get many rules for minimum support of 0.0001 and minimum threshold of 0.0015. More rules means better association of items and their chance of reccurence. Here we have a maximum support for id 1669 and date 19-08-2015 combination(s = 0.000232 and confidence = 1).')
print ('Case 1 Output:')
res=association_rules(frequent_itemsets, metric="confidence", min_threshold=0.0015)
print('***************Printing all rules:*****************')
print(res)
print('*****************Getting highest confidence*****************')
res1=res[['antecedents','consequents','support','confidence','lift']]
print("Returning the items and itemsets with equal to 100% confidence:")
res1[res1['confidence']==1]

# # # # # # # # #  Code for Task 3, Case:1 # # # # # # # # #
Case 1 (minimum support=0.001)
Case 1 Reasoning: We get 439720 rules for minimum support of 0.000275 and minimum threshold of 0.0015. More rules means better association of items and their chance of reccurence. Here we have a maximum support for mineral water and spaghetti combination(0.059725)
Case 1 Output:
***************Printing all rules:*****************
             antecedents         consequents  antecedent support  \
0     (other vegetables)        (21-07-2015)            0.048962
1           (21-07-2015)  (other vegetables)            0.002399
2          (canned beer)        (21-07-2015)            0.018496
3           (21-07-2015)       (canned beer)            0.002399
4                 (soda)        (21-07-2015)            0.039056
...                  ...                 ...                 ...
7175        (28-06-2014)              (2603)            0.001238
7176        (13-05-2014)              (4005)            0.001625
7177              (4005)        (13-05-2014)            0.000103
7178              (3108)        (25-03-2014)            0.000103
7179        (25-03-2014)              (3108)            0.001238

      consequent support   support  confidence        lift  leverage  \
0               0.002399  0.000155    0.003161    1.317686  0.000037
1               0.048962  0.000155    0.064516    1.317686  0.000037
2               0.002399  0.000155    0.008368    3.488100  0.000110
3               0.018496  0.000155    0.064516    3.488100  0.000110
4               0.002399  0.000155    0.003963    1.651894  0.000061
...                  ...       ...         ...         ...       ...
7175            0.000103  0.000103    0.083333  807.604167  0.000103
7176            0.000103  0.000103    0.063492  615.317460  0.000103
7177            0.001625  0.000103    1.000000  615.317460  0.000103
7178            0.001238  0.000103    1.000000  807.604167  0.000103
7179            0.000103  0.000103    0.083333  807.604167  0.000103

      conviction
0       1.000765
1       1.016627
2       1.006020
3       1.049194
4       1.001570
...          ...
7175    1.090797
7176    1.067686
7177         inf
7178         inf
7179    1.090797

[7180 rows x 9 columns]
*****************Getting highest confidence*****************
Returning the items and itemsets with at least 85% confidence:

             antecedents   consequents   support  confidence         lift
122               (1974)    (3/5/2015)  0.000129         1.0   680.087719
220               (4918)  (27-01-2015)  0.000129         1.0   553.785714
506               (4829)   (3/11/2015)  0.000129         1.0   692.232143
839               (1024)   (10/8/2015)  0.000103         1.0   901.511628
3671              (2002)  (20-10-2015)  0.000181         1.0  1047.702703
3808              (1669)  (19-08-2015)  0.000232         1.0   646.083333
3855              (2208)  (30-07-2015)  0.000206         1.0   657.033898
3879              (3228)  (26-01-2015)  0.000206         1.0   516.866667
3881              (2368)  (11/11/2015)  0.000206         1.0   646.083333
3885              (4701)  (30-04-2015)  0.000206         1.0   425.989011
4026              (1112)    (9/4/2015)  0.000103         1.0   692.232143
4531              (2767)  (27-01-2015)  0.000129         1.0   553.785714
4567              (2634)  (22-04-2015)  0.000129         1.0   635.491803
4620              (2891)    (2/7/2015)  0.000129         1.0   807.604167
4831              (1953)    (9/3/2015)  0.000103         1.0   791.122449
4946              (3434)   (10/6/2015)  0.000129         1.0   731.415094
4983              (2833)  (14-08-2015)  0.000103         1.0   717.870370
5153              (3412)  (26-01-2015)  0.000103         1.0   516.866667
5194              (3055)  (18-08-2015)  0.000181         1.0   472.743902
5217              (4175)  (29-01-2015)  0.000181         1.0   922.976190
5237  (1994, whole milk)   (11/3/2015)  0.000103         1.0   704.818182
5339              (4768)  (13-03-2015)  0.000103         1.0   545.985915
5400              (1459)  (18-07-2015)  0.000103         1.0  1047.702703
5510              (1177)  (14-10-2015)  0.000103         1.0   538.402778
5575              (2179)  (16-04-2015)  0.000103         1.0   824.787234
5624              (2429)  (29-06-2015)  0.000103         1.0   605.703125
5652              (3152)  (24-11-2015)  0.000103         1.0   516.866667
5679              (4731)    (4/4/2015)  0.000155         1.0   745.480769
5735              (3853)    (4/7/2015)  0.000155         1.0   635.491803
5746              (4053)  (22-03-2015)  0.000155         1.0   615.317460
5793              (3440)  (21-12-2015)  0.000155         1.0  1336.724138
5836              (3995)  (26-06-2015)  0.000103         1.0   901.511628
5857              (1812)  (14-10-2015)  0.000103         1.0   538.402778
5861              (2378)  (15-04-2015)  0.000103         1.0   635.491803
5870              (1960)    (9/1/2015)  0.000103         1.0   538.402778
5891              (2214)  (19-01-2015)  0.000103         1.0   731.415094
7036              (3792)  (30-07-2014)  0.000103         1.0   717.870370
7046              (1433)  (22-09-2014)  0.000103         1.0  1107.571429
7073              (1402)  (14-10-2014)  0.000103         1.0   646.083333
7083              (3628)    (1/8/2014)  0.000155         1.0   791.122449
7102              (4490)  (21-01-2014)  0.000103         1.0   657.033898
7152              (1359)  (29-05-2014)  0.000103         1.0   538.402778
7161              (3335)    (5/9/2014)  0.000103         1.0   704.818182
7162              (3040)  (11/10/2014)  0.000103         1.0   578.582090
7164              (3627)    (6/7/2014)  0.000103         1.0   680.087719
7174              (2603)  (28-06-2014)  0.000103         1.0   807.604167
7177              (4005)  (13-05-2014)  0.000103         1.0   615.317460
7178              (3108)  (25-03-2014)  0.000103         1.0   807.604167

In [66]:
print ('# # # # # # # # #  Code for Task 3, Case:2 # # # # # # # # #') 
print ('Case 2 (minimum support=0.01)')
print ('Case 2 Reasoning: At a glance, there are many rules with confidence = 1. We get many rules for minimum support of 0.0001 and minimum threshold of 0.0015. More rules means better association of items and their chance of reccurence. Here we have a maximum support for id 1669 and date 19-08-2015 combination(s = 0.000232 and confidence = 1).')
print ('Case 2 Output:')
frequent_itemsets=fpgrowth(df, min_support=0.000025, use_colnames=True)
res=association_rules(frequent_itemsets, metric="confidence", min_threshold=0.5)
print('***************Printing all rules:*****************')
print(res)
print('*****************Getting highest confidence*****************')
res1=res[['antecedents','consequents','support','confidence','lift']]
print("Returning the items and itemsets with confidence: 100% and support:0.02%")
res2= res1[res1['support']>=0.0002]
res2[res2['confidence']==1]

# # # # # # # # #  Code for Task 3, Case:2 # # # # # # # # #
Case 2 (minimum support=0.01)
Case 2 Reasoning:  At a glance, there are many rules with confidence = 1. We get many rules for minimum support of 0.0001 and minimum threshold of 0.0015. More rules means better association of items and their chance of reccurence. Here we have a maximum support for id 1669 and date 19-08-2015 combination(s = 0.000232 and confidence = 1).
Case 2 Output:
***************Printing all rules:*****************
                                antecedents                 consequents  \
0                    (1808, tropical fruit)                (21-07-2015)
1                          (4/2/2015, 1808)  (long life bakery product)
2      (4/2/2015, long life bakery product)                      (1808)
3          (long life bakery product, 1808)                  (4/2/2015)
4                              (meat, 1808)                (29-11-2014)
...                                     ...                         ...
87221            (3/11/2014, spread cheese)                      (2417)
87222                                (2417)  (3/11/2014, spread cheese)
87223                     (2417, 3/11/2014)                (newspapers)
87224                    (2417, newspapers)                 (3/11/2014)
87225                                (2417)     (3/11/2014, newspapers)

       antecedent support  consequent support   support  confidence  \
0                0.000026            0.002399  0.000026         1.0
1                0.000052            0.006939  0.000026         0.5
2                0.000052            0.000258  0.000026         0.5
3                0.000026            0.001083  0.000026         1.0
4                0.000026            0.001212  0.000026         1.0
...                   ...                 ...       ...         ...
87221            0.000026            0.000052  0.000026         1.0
87222            0.000052            0.000026  0.000026         0.5
87223            0.000052            0.015375  0.000026         0.5
87224            0.000026            0.001238  0.000026         1.0
87225            0.000052            0.000077  0.000026         0.5

               lift  leverage  conviction
0        416.827957  0.000026         inf
1         72.053903  0.000025    1.986122
2       1938.250000  0.000026    1.999484
3        922.976190  0.000026         inf
4        824.787234  0.000026         inf
...             ...       ...         ...
87221  19382.500000  0.000026         inf
87222  19382.500000  0.000026    1.999948
87223     32.520973  0.000025    1.969251
87224    807.604167  0.000026         inf
87225   6460.833333  0.000026    1.999845

[87226 rows x 9 columns]
*****************Getting highest confidence*****************
Returning the items and itemsets with confidence: 100% and support:0.02%

      antecedents   consequents   support  confidence        lift
42544      (1669)  (19-08-2015)  0.000232         1.0  646.083333
43026      (2208)  (30-07-2015)  0.000206         1.0  657.033898
43258      (3228)  (26-01-2015)  0.000206         1.0  516.866667
43270      (2368)  (11/11/2015)  0.000206         1.0  646.083333
43317      (4701)  (30-04-2015)  0.000206         1.0  425.989011

In [69]:
print ('# # # # # # # # #  Code for Task 3, Case:3 # # # # # # # # #') 
print ('Case 3 (minimum support=0.001)')
print ('Case 3 Reasoning: We get very less rules for minimum support of 0.00005 and but with very strong confidence of 1.0 at min confidence threshhold 0.07. Here we have a maximum support of 0.000232 with confidence 1.Rule is with antecedent 1669 and consequent as 19-08-2015')
print ('Case 3 Output:')
frequent_itemsets=fpgrowth(df, min_support=0.00005, use_colnames=True)
res = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.07)
print('***************Printing all rules:*****************')
print(res)
print('*****************Getting highest confidence*****************')
res1=res[['antecedents','consequents','support','confidence','lift']]
print("Returning the items and itemsets with confidence: 100% and support:0.02%")
res2= res1[res1['support']>=0.0002]
res2[res2['confidence']==1]

# # # # # # # # #  Code for Task 3, Case:3 # # # # # # # # #
Case 3 (minimum support=0.001)
Case 3 Reasoning: We get very less rules for minimum support of 0.00005 and but with very strong confidence of 1.0 at min confidence threshhold 0.07. Here we have a maximum support of 0.000232 with confidence 1.Rule is with antecedent 1669 and consequent as 19-08-2015
Case 3 Output:
***************Printing all rules:*****************
      antecedents   consequents  antecedent support  consequent support  \
0          (1808)  (21-07-2015)            0.000258            0.002399
1          (1808)    (4/2/2015)            0.000258            0.001083
2          (1808)  (29-11-2014)            0.000258            0.001212
3          (1808)  (15-12-2014)            0.000258            0.001238
4      (5/1/2015)  (whole milk)            0.001754            0.064543
...           ...           ...                 ...                 ...
24160      (4590)  (19-08-2014)            0.000052            0.001238
24161      (4703)  (20-10-2014)            0.000052            0.001264
24162      (3607)  (22-02-2014)            0.000052            0.001651
24163      (4587)  (23-05-2014)            0.000052            0.001419
24164      (2417)   (3/11/2014)            0.000052            0.001238

        support  confidence        lift  leverage  conviction
0      0.000077    0.300000  125.048387  0.000077    1.425144
1      0.000052    0.200000  184.595238  0.000051    1.248646
2      0.000052    0.200000  164.957447  0.000051    1.248484
3      0.000077    0.300000  242.281250  0.000077    1.426803
4      0.000155    0.088235    1.367083  0.000042    1.025985
...         ...         ...         ...       ...         ...
24160  0.000052    1.000000  807.604167  0.000052         inf
24161  0.000052    1.000000  791.122449  0.000052         inf
24162  0.000052    1.000000  605.703125  0.000052         inf
24163  0.000052    1.000000  704.818182  0.000052         inf
24164  0.000052    1.000000  807.604167  0.000052         inf

[24165 rows x 9 columns]
*****************Getting highest confidence*****************
Returning the items and itemsets with confidence: 100% and support:0.02%

      antecedents   consequents   support  confidence        lift
12165      (1669)  (19-08-2015)  0.000232         1.0  646.083333
12323      (2208)  (30-07-2015)  0.000206         1.0  657.033898
12389      (3228)  (26-01-2015)  0.000206         1.0  516.866667
12396      (2368)  (11/11/2015)  0.000206         1.0  646.083333
12416      (4701)  (30-04-2015)  0.000206         1.0  425.989011

# References

[01] https://www.kaggle.com/acostasg/random-shopping-cart

[02] https://github.com/asaini/Apriori

[03] https://towardsdatascience.com/the-fp-growth-algorithm-1ffa20e839b8

# Rubric
* [02 points] - Student Details 
* [08 points] - Comply with submission instructions 
* [20 points] - DataSet Preprocess for Apriory.py  
* [20 points] - Run Apriory.py
* [20 points] - DataSet Preprocess for  FPgrowth
* [30 points] - Run FPgrowth